### ISSUE TITLE
Polymorphic type causes segfault?

### ISSUE THREAD

**Issue by helanhalvan** [parapluu/encore#634]
Full code https://github.com/helanhalvan/backup/commit/479bf8b02f0ccb67e9354f38a036bbe7da5a5f99

Easier to run code https://github.com/helanhalvan/backup/commit/d01b6cf0e39ce74536552e111b64a6af0c1636b5

(does not use SDL, contains my version of encorec)

While attempting to work around the lack of actor-faces, I tried to use passive classes to wrap my active classes, and use the existing traits system to get actor-faces. You can see the result in Box.enc. Basically, NAME_face is a wrapper for an active object named NAME. The wrappers return futures instead of values. For being a boilerplate workaround it's quite nice.

Anyway, when using this code, I get a segfault. This is what gdb give me:

```
WORKED!
(0, 60, 40, 60, 0, 60, 2000)
[New Thread 0x7fffdb33c700 (LWP 7035)]
(160, 60, 50, 30, 160, 60, 2000)
checking
constructor-done!
top-imp-done
top-setup-done
START
Box.Box_face@0x7fffc3cd3000

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdb33c700 (LWP 7035)]
0x00000000004183d2 in _enc__method__encore_libs_master_Ped_util_Box_Top_Box_start (
    _ctx=0x7fffdb33a880, _this=0x7fffe3b14400) at main_src/Top_Box.encore.c:239
239	main_src/Top_Box.encore.c: No such file or directory.
(gdb) backtrace
#0  0x00000000004183d2 in _enc__method__encore_libs_master_Ped_util_Box_Top_Box_start (
    _ctx=0x7fffdb33a880, _this=0x7fffe3b14400) at main_src/Top_Box.encore.c:239
#1  0x000000000041a229 in _enc__dispatch__encore_libs_master_Ped_util_Box_Top_Box (
    _ctx=0x7fffdb33a880, _a=0x7fffe3b14400, _m=0x7fffe39644c0) at main_src/Top_Box.encore.c:914
#2  0x000000000043cec6 in handle_message (ctx=0x7fffdb33a880, actor=0x7fffe3b14400, 
    msg=<optimized out>) at libponyrt/actor/actor.c:129
#3  0x000000000043d0bb in ponyint_actor_run (ctx=ctx@entry=0x7fffdb33a880, 
    actor=actor@entry=0x7fffe3b14400, batch=batch@entry=100) at libponyrt/actor/actor.c:218
#4  0x0000000000440e10 in run (sched=sched@entry=0x7ffff533dbc0) at libponyrt/sched/scheduler.c:306
#5  0x00000000004411d3 in run_thread (arg=0x7ffff533dbc0) at libponyrt/sched/scheduler.c:435
#6  0x00007ffff746f184 in start_thread (arg=0x7fffdb33c700) at pthread_create.c:312
#7  0x00007ffff6a7c37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

I have looked at `Top_Box.encore.c:239` and it does not give me anything. After adding a bunch of print-outs, I am fairly shore I know where the error comes from. Looking at `line 99 in box.enc`

```
    def start() : void {print("START\n"); print(this.implementation); this.implementation.start(); print("ING\n");} 

```

The last printout I get is the print of `this.implementation`, which is of type `Box_face` which is to be expected. However, the "real" type is known to be `Multi_Box_face`, (see `Box.enc line 86`). Therefore, you can change the type of `implementation`to `Multi_Box_face`. When you do, the program behaves differently, and completes normally. 

From that, it seems like it's the fact that the call is done on something of type `Box_face` and not on something of type `Multi_Box_face` which does all the difference, which it really shouldn't, considering both versions compile. It does not seem like the method `start():void` in `Multi_Box_face` does run anyway, as there is no printout of `multi_start` when running the seg-faulting version. 

I have tried to re-create this issue, but running some very similar code does not cause issues. For completeness, this code does run, and uses the same pattern:

Imported module:

```
module Class
class Foo {
    x : int
    def fun() : void { print("ACTIVE_OBJECT_POLLYMORPHISM!\n") }
    def boor() : int { this.x }
}
class Other {
    y : (int,int)
    def fun() : void { print("SOMETHING ELSE!\n") }
    def boor() : int { 3 }
}
class More {
    z : (int,int,int)
    def fun() : void { print("MoRe!\n") }
    def boor() : int { 12 }
}
passive class Foo_Face : Face {
    t : Foo
    def init(t:Foo) : void {
        this.t=t
    }
    def fun() : void {this.t.fun()}
    def boor() : Fut int { this.t.boor() }
}
passive class Other_Face : Face {
    t : Other
    def init(t:Other) : void {
        this.t=t
    }
    def fun() : void {this.t.fun()}
    def boor() : Fut int { this.t.boor() }
}
passive class More_Face : Face {
    t : More
    def init(t:More) : void {
        this.t=t
    }
    def fun() : void {this.t.fun()}
    def boor() : Fut int { this.t.boor() }
}

trait Face {
    require fun() : void
    require boor() : Fut int
}

```

main:

```
import Class
class Main {
    a : Foo
    b : Foo_Face
    c : Face
    def main() : void {
            let x = rand()%100;
            print(x);
            this.a = new Foo();
            this.b = new Foo_Face(new Foo());
            this.c = if (x>99) then new Foo_Face(new Foo()) else new Other_Face(new Other);
            this.a.fun();
            this.b.fun();
            this.c.fun();
            this!do()
    }
    def do() : void {
            print(this.a);
            print(this.b);
            print(this.c);
            this.a.fun();
            this.b.fun();
            this.c.fun();
    }
}
def rand() : int {
    let x=0;
    embed void { #{x}=rand(); } end;
    x
}
```
Me and Kiko did some investigation using gdb, running a slightly different version which have the same problem. 

```
(gdb) backtrace
#0  0x000000000041954b in _enc__method__encore_libs_master_Ped_util_Box_Multi_Box_start (_ctx=0x7fffdbb3a880, _this=0x7fffdb33c400) at Multi_Box.encore.c:937
...
(gdb) p _a_3
$6= (_enc__trait__encore_libs_master_Ped_util_Box_Box_face_t *) 0x7fffe3b11c20
p *_a_3
$7 = {_enc__self_type = 0x11}
(gdb) p _a_3->_enc__self_type
$8 = (pony_type_t *) 0x11
(gdb) p *(_a_3->_enc__self_type)
Cannot access memory at address 0x11
(gdb) p _a_3->_enc__self_type->vtable
Cannot access memory at address 0x79
(gdb) p *(_a_3->_enc__self_type->vtable)
Cannot access memory at address 0x79
```
related C code, the function that crashes:

```
void* _enc__method__encore_libs_master_Ped_util_Box_Multi_Box_start(pony_ctx_t** _ctx, _enc__active__encore_libs_master_Ped_util_Box_Multi_Box_t* _this)
{
  /* print("start\n") */;
  char* _literal_0 = "start\n";
  printf("%s", _literal_0);
  /* for a in this.multi
  {println(a);
   a.start()} */;
  void* _for_1;
  array_t* _fieldacc_8 = (*_this)._enc__field_multi;
  int64_t _start_4 = 0;
  int64_t _stop_5 = (array_size(_fieldacc_8) - 1);
  int64_t _src_step_7 = 1;
  int64_t _literal_9 = 1;
  int64_t _step_6 = (_literal_9 * _src_step_7);
  range_assert_step(_step_6);
  int64_t _index_2;
  if ((_step_6 > 0))
  {
    _index_2 = _start_4;
  }
  else
  {
    _index_2 = _stop_5;
  };
  while (((_index_2 >= _start_4) && (_index_2 <= _stop_5)))
  {
    _enc__trait__encore_libs_master_Ped_util_Box_Box_face_t* _a_3 = array_get(_fieldacc_8, _index_2).p;
    /* println(a) */;
    printf("Box.Box_face@%p\n", _a_3); //LAST PRINTOUT
    /* a.start() */;
    check_receiver(_a_3, ".", "a", "start", "\"./encore-libs-master/Ped_util/Box.enc\" (line 210, column 24)");
    void* (*_Box_face_start_10) (pony_ctx_t**, _enc__trait__encore_libs_master_Ped_util_Box_Box_face_t*);
    void* (*_Box_face_vtable_11) (int);
    _Box_face_vtable_11 = ((void*) _a_3->_enc__self_type->vtable); //LINE THAT CRASHES
    _Box_face_start_10 = _Box_face_vtable_11(_ENC__MSG__encore_libs_master_Ped_util_Box_Box_face_start);
    void* _trait_method_call_12 = _Box_face_start_10(_ctx, 
((_enc__trait__encore_libs_master_Ped_util_Box_Box_face_t*) _a_3));
    _for_1 = _trait_method_call_12;
    _index_2 = (_index_2 + _step_6);
  };
  /* print("ing\n") */;
  char* _literal_13 = "ing\n";
  printf("%s", _literal_13);
  return UNIT;
}
```
So it seems like the issue is that some part(s) of `_a_3` have really bad pointer values. Why that is I don't know.

**Comment by supercooldave** [comment]
Unclear whether this is still an issue. Possibly fixed. Too hard to tell.
